### ISSUE TITLE
Version Latest no incluye onepay

### ISSUE THREAD

**Issue by MaestroKongrio** [TransbankDevelopers/transbank-sdk-python#102]
La version latest del SDK (4.0.1) no incluye el soporte para los métodos referidos a onepay, incluidos en la integración de ejemplo OnePay-Python SDK incluida en este github. Hay que hacer un downgrade a la version 1.0.1 para que el soporte de OnePay funcione. Aunque no es estrictamente un bug, es algo incómodo e inesperado al trabajar.
Gracias.

**Comment by otrab** [comment]
Estimado

Esto no es incluido ya que OnePay ya no se integra directamente.
Para utilizarlo debes solicitar a soporte@transbank.cl que agreguen como medio de pago al código de comercio que están usando.


Saludos!
