### ISSUE TITLE
Error de SSL

### ISSUE THREAD

**Issue by tomisanhues2** [TransbankDevelopers/transbank-sdk-python#130]
**Describe el bug**

HTTPSConnectionPool(host='webpay3gint.transbank.cl', port=443): Max retries exceeded with url: /rswebpaytransaction/api/oneclick/v1.2/transactions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)')))

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: [e.g. 1.1.0] 5.0.0
- Python: [e.g. 3.4] Python3.11

**Contexto adicional**

Por ahora solo probado en ambiente de desarrollo de Postman.

**Comment by mastudillot** [comment]
Hola, ya no te pasa el problema?

**Comment by tomisanhues2** [comment]
No, al parece transbank tenía algun problema a nivel nacional. Se solucionó solo el tema de los certificados.
