### ISSUE TITLE
Status de una transacción en estado INITIALIZED

### ISSUE THREAD

**Issue by wcartayad** [TransbankDevelopers/transbank-sdk-python#75]
El error se produce al crear una transacción e inmediatamente hacer el check del status de la transacción.

Puede que no sea algo común de que se haga ese flujo, pero es un requerimiento en mi proyecto.

Gracias de antemano

**Comment by gonzunigad** [comment]
Hola @wcartayad . No entenedí bien el problema. ¿Me explicas nuevamente?

**Comment by ffiebig** [comment]
Arreglado en la 1.4.0
