### ISSUE TITLE
Webpay Plus Mall - Al actualizar página previa a pago, se vuelve a agregar la transacción a la ya existente

### ISSUE THREAD

**Issue by jalvaradosegura** [TransbankDevelopers/transbank-sdk-python#77]
**Descripción**

Si uno actualiza la url en donde se crea el detalle de transacción y transacción, se vuelve a agregar la transacción a la transacción ya existente. Es decir si estoy a punto de pagar $1.000 y actualizo, tendré $2.000 a pagar, si vuelvo a actualizar $3.000 y así sucesivamente.
 
**Para reproducir**

1. Descargar el ejemplo de este sdk: https://github.com/TransbankDevelopers/transbank-sdk-python-webpay-rest-example (yo lo implementé en Django, ahí me di cuenta. Luego lo probé en el ejemplo y pasaba lo mismo).
2. Seguir instrucciones para ejecutar el ejemplo.
3. Ir a http://localhost:5000/
4. Presionar "Crear Transacción" (Webpay Plus Mall)
5. Presionar "Aceptar"
6. **Aquí ocurre el problema**, si actualizan la página en la que están (que debiese ser http://localhost:5000/webpay-plus-mall/create), los productos se duplicaran, para ser más exacto, se volverá a agregar la transacción a la ya existente.
7. Otra forma de que ocurra este problema es: al llegar al paso 5, se detienen, abren otra pestaña y repiten el flujo desde el paso 1. Al llegar al paso 5, estará todo "duplicado".

**Comportamiento esperado**

Es primera vez que intento implementar pago con Transbank, pero creo que el comportamiento debiese ser que no se agregara de nuevo a la cola, que al crear la transacción, estuviera siempre lo mismo (a menos el que consumidor agregue más cosas).

**Versiones**
- SDK: 1.3.0
- Python: 3.8.0

**Creo que aquí puede estar el problema**
No tengo certeza de cómo funciona el sdk, pero creo que el problema puede estar en la clase `MallTransactionCreateDetails`. ([Aquí](https://github.com/TransbankDevelopers/transbank-sdk-python/blob/master/transbank/webpay/webpay_plus/request/__init__.py#L54))

Cada vez que se instancia un objeto de esa clase, se agregarán los detalles al atributo de clase `__details`. Creo que por eso puede estar pasando.

El comportamiento es algo similar a lo siguiente:
```py
class Something:
    _details = []

    def __init__(self, amount):
        self.add(amount)

    def add(self, amount):
        self._details.append(amount)
        return self


# Primera carga de la página
something = Something(1000)
print(something._details)
# output:
# [1000]

# Segunda carga de la página
something = Something(1000)
print(something._details)
# output:
# [1000, 1000]
```

**Comment by jalvaradosegura** [comment]
Generé este [PR](https://github.com/TransbankDevelopers/transbank-sdk-python/pull/78) para el request

**Comment by gonzunigad** [comment]
Gracias por el PR! 🎉
