### ISSUE TITLE
No se puede hacer from transbank.webpay.webpay_plus import WebpayPlus

### ISSUE THREAD

**Issue by dansanti** [TransbankDevelopers/transbank-sdk-python#81]
**Describe el bug**

Una descripción concisa sobre el bug.
 `
>>> from transbank.webpay.webpay_plus import WebpayPlus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'WebpayPlus'
`

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: [1.3] (desde repo pip)
- Python: [3.6]

**Contexto adicional**

Agrega cualquier otro información sobre el problema aquí.

**Comment by santcosta** [comment]
Me pasa lo mismo ! Estuve revisando los archivos y la ultima version de pip no es la ultima de git. (o por lo menos hay diferencias)

Saludos

**Comment by jparevalo** [comment]
Mismo problema, no logro usar el SDK pues no puedo importar webpay, ni webpay_plus. Si lo hago de la forma reportada por @dansanti me pasa igual, no puedo importar WebpayPlus

**Comment by isabellaahc** [comment]
@dansanti @santcosta @jparevalo, gracias por reportar este error. 
Lo revisaremos lo antes posible.

**Comment by santcosta** [comment]
@jparevalo Lo que podes hacer por mientras es actualizar el sdk de forma manual. Si lo instalaste via pip buscalo en tu sistema 
find / -name "transbank" 2>/dev/null y reemplaza la carpeta de transbank por el repo de git.

**Comment by jparevalo** [comment]
@santcosta gracias por el tip, funcionó hasta cierto punto, logré settear la config principal pero no logro dar con el "create" para iniciar la transacción. Alguna idea?
este bloque de la documentación no me funciona ni calza con lo que hay en el repo:

`response = transbank.webpay.webpay_plus.create(buy_order, session_id, amount, return_url)`

**Comment by isabellaahc** [comment]
Hola! @jparevalo, @dansanti , @santcosta 
Acaba de actualizarse el package con la última versión del sdk (1.4.0).
Por favor si siguen presentando inconvenientes nos comentan 👍 

Voy a esperar el feedback antes de dar cierre a este issue.

**Comment by dansanti** [comment]
Hola, sí confirmo que en la última update se reparó, gracias

**Comment by SetRac** [comment]
A mi en python3.10 no me funciona da el mismo error no se si cambiaron la forma de acceder a WebpayPlus
from transbank.webpay.webpay_plus import WebpayPlus
ImportError: cannot import name 'WebpayPlus' from 'transbank.webpay.webpay_plus' (/usr/local/lib/python3.10/dist-packages/transbank/webpay/webpay_plus/__init__.p

ESto es par odoo v17 y python 3.10

**Comment by zanyko** [comment]
Me funcionó. El problema era que ya no es necesario usar:

from transbank.webpay.webpay_plus import WebpayPlus

#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Installen el SDK, solo importen esto y declaren 'transaction' como variable global':

```
from transbank.webpay.webpay_plus.transaction import Transaction
from transbank.common.integration_type import IntegrationType

transaction = Transaction.build_for_integration(
    commerce_code='597055555532',
    api_key='579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
)
```


Esa es una key pública de Transbank para entornos de desarrollo.

#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Ejemplo de una función en Python en la que se utiliza la variable global:

```
def pagoIniciar(request, id):
    preview = get_object_or_404(Preview, id=id)  # Obtén la compra
    total = preview.total  # Total a pagar

    # Crear una transacción con Webpay

    transaccion = transaction  # aqui se usa la variable global para crear 'transaccion'

    response = transaccion.create(
        buy_order=str(preview.id),      # ID único de la compra
        session_id=str(request.user.id),    # ID del usuario
        amount=total,  # Monto total
        return_url=request.build_absolute_uri('/pagoExito/'),  # URL de retorno en caso de éxito
    )

    # Guardar el token de la transacción en la sesión
    request.session['webpay_token'] = response['token']

    # Redirigir al usuario a Webpay para completar el pago
    return redirect(response['url'] + '?token_ws=' + response['token'])
```
